// Package declaration for the FIR phase of the ViewBinding compiler plugin.
package com.adkhambek.viewbinding.compiler.fir

// Import the base class for generated declaration keys.
import org.jetbrains.kotlin.GeneratedDeclarationKey

// Marker object used to identify declarations generated by the ViewBinding compiler plugin.
// Every FIR declaration generated by this plugin (the `binding` property) is tagged with this key.
// This allows the IR phase (ViewBindingIrElementTransformer) to identify which properties
// need body generation and distinguishes ViewBinding-generated declarations from Screen-generated ones.
object ViewBindingDeclarationKey : GeneratedDeclarationKey()
