// Package declaration for the FIR phase of the Screen compiler plugin.
package com.adkhambek.screen.compiler.fir

// Import the base class for generated declaration keys used to tag plugin-generated declarations.
import org.jetbrains.kotlin.GeneratedDeclarationKey

// Marker object used to identify declarations generated by the Screen compiler plugin.
// Every FIR declaration (companion object, property, function) generated by this plugin
// is tagged with this key. This allows:
//   1. The IR phase to identify which declarations need body generation
//   2. The FIR infrastructure to track the origin of generated declarations
//   3. Other plugins or IDE features to distinguish generated vs. user-written declarations
// The key is checked in ScreenIrElementTransformer.visitProperty() and visitSimpleFunction()
// to determine if a declaration was generated by this plugin and needs IR body generation.
object ScreenDeclarationKey : GeneratedDeclarationKey()
